apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  namespace: developer
  name: tanzu-java-web-app-default
  labels:
    apps.tanzu.vmware.com/tap-ns: developer
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    app.kubernetes.io/part-of: tanzu-java-web-app-default
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "11"
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/askanonymous/tanzu-java-web-app-abhi
      ref:
        branch: main
